name: ryu-cho

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  ryu-cho:
    name: Ryu Cho
    runs-on: ubuntu-latest
    steps:
      - uses: vuejs-translations/ryu-cho@v1
        with:
          # â†“ personal access token (classic) with `public_repo` scope
          access-token: ${{ secrets.RYU_CHO_ACCESS_TOKEN }}
          username: ${{ secrets.RYU_CHO_USER_NAME }}
          email: ${{ secrets.RYU_CHO_USER_EMAIL }}
          upstream-repo: https://github.com/vuejs-translations/docs-ja.git
          upstream-repo-branch: main
          head-repo: https://github.com/vuejs/docs
          head-repo-branch: main
          track-from: b27e90689cb81114317fda8d6f9099ad4d68590c
          # path-starts-with: src/
          workflow-name: ryu-cho
